/*
 * File: app/store/WorkforceAllocation.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ForecastingSystem.store.WorkforceAllocation', {
    extend: 'Ext.data.Store',

    requires: [
        'ForecastingSystem.model.WorkforceAllocation'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'ForecastingSystem.model.WorkforceAllocation',
            storeId: 'time',
            data: [
                {
                    time: 8,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 9,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 10,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 11,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 12,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 13,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 14,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 15,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 16,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 17,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 18,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                },
                {
                    time: 19,
                    na: 0,
                    oo: 0,
                    sl: 0,
                    qp: 0
                }
            ]
        }, cfg)]);
    }
});