/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'ForecastType',
        'ForecastSelection',
        'ServiceInfo',
        'ComparisonItem',
        'ForecastingResult',
        'ErlangResult',
        'WorkforceAllocation',
        'SelectionContent',
        'CommandResult',
        'Configuration'
    ],
    stores: [
        'TypeList',
        'SelectionList',
        'ForecastingResult',
        'ServiceInfo',
        'TrafficForecasting',
        'ATTForecasting',
        'TrafficComparison',
        'ATTComparison',
        'Erlang8',
        'WorkforceAllocation',
        'Erlang9',
        'SelectionContent',
        'Erlang10',
        'Erlang11',
        'Erlang12',
        'Erlang13',
        'Erlang14',
        'Erlang15',
        'Erlang16',
        'Erlang17',
        'Erlang18',
        'Erlang19',
        'OptionalSelection',
        'CombinationSelection',
        'CombinationType',
        'CommandResult',
        'Configuration'
    ],
    views: [
        'MyViewport'
    ],
    autoCreateViewport: true,
    name: 'ForecastingSystem'
});
